/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Willydmq
 */
//import javax.swing.table.DefaultTableModel;
import modelo.Lote;
import controlador.LoteControl;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
//import java.sql.Connection;
//import java.sql.PreparedStatement;
import java.sql.ResultSet;
//import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
//import java.util.List;
//import javax.swing.DefaultComboBoxModel;
//import javax.swing.JComboBox;
//import javax.swing.JOptionPane;
//import modelo.Conexion;
//import modelo.Conectar;
import modelo.Producto;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class LoteFormulario extends javax.swing.JFrame {

//    DefaultTableModel Tlote;
    LoteControl servicio = new LoteControl();
//    public List<Producto> productos;
//    Producto pro = new Producto() {
//    };
    //private Conexion conn = null;
    //private Statement stm = null;
    private ResultSet rs = null;
//    //private Connection con = null;
//    private PreparedStatement ps = null;
//    private Conectar conn = null;

    /**
     * Creates new form LoteFormulario
     */
    public LoteFormulario() {
	initComponents();
	cargarCombo();
	AutoCompleteDecorator.decorate(jcbNombre);

	//jcbOculto.setVisible(false);
    }

    private void cargarCombo() {
	servicio.listarLote(jcbNombre);
	txtId.setEnabled(false);
    }

//    private void cargarCombo() {
//	LoteControl loControl = new LoteControl();
//	ArrayList<Producto> nombreProductos = loControl.listarProducto();
//	jcbNombre.removeAllItems();
//	jcbNombre.addItem("Seleciones un Producto");
//	
//	for (int i = 0; i < nombreProductos.size(); i++) {
//	    jcbNombre.addItem(nombreProductos.get(i).getNombre_pro());
////	    jcbNombre.equals(nombreProductos.get(i).getNombre_pro());
////	    txtId.setText(l.getId_lot());
//	}
//    }
//    private void cargarCombo() {
//	conn = new Conexion();
//	con = conn.getCon();
//	String sql = "SELECT * FROM producto";
//	jcbNombre.removeAllItems();
//	jcbNombre.addItem("Seleciones un Producto");
//	try {
//	    stm = conn.getCon().createStatement();
//	    rs = stm.executeQuery(sql);
//	    while (rs.next()) {
//		String nombre_pro = rs.getString("nombre_pro");
//		jcbNombre.addItem(nombre_pro);
//	    }
//
//	} catch (Exception e) {
//	    JOptionPane.showMessageDialog(null, e);
//	}
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre_Lote = new javax.swing.JLabel();
        jcbNombre = new javax.swing.JComboBox<>();
        btnEliminar_Lote = new javax.swing.JButton();
        btnModificar_Lote = new javax.swing.JButton();
        btnAgregar_Lote = new javax.swing.JButton();
        txtLote = new javax.swing.JTextField();
        lblLote = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblId_Lote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(80, 160));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        lblNombre_Lote.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNombre_Lote.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre_Lote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/name_user_3716.png"))); // NOI18N
        lblNombre_Lote.setText("Nombre:");

        jcbNombre.setBackground(new java.awt.Color(255, 153, 102));
        jcbNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcbNombre.setForeground(new java.awt.Color(51, 51, 51));
        jcbNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbNombreItemStateChanged(evt);
            }
        });
        jcbNombre.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbNombrePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jcbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNombreActionPerformed(evt);
            }
        });

        btnEliminar_Lote.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminar_Lote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar_Lote.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminar_Lote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/trash_bin_icon-icons.com_67981.png"))); // NOI18N
        btnEliminar_Lote.setText("Eliminar");
        btnEliminar_Lote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_LoteActionPerformed(evt);
            }
        });

        btnModificar_Lote.setBackground(new java.awt.Color(153, 255, 153));
        btnModificar_Lote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar_Lote.setForeground(new java.awt.Color(51, 51, 51));
        btnModificar_Lote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/edit_modify_icon_149489.png"))); // NOI18N
        btnModificar_Lote.setText("Modificar");
        btnModificar_Lote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar_LoteActionPerformed(evt);
            }
        });

        btnAgregar_Lote.setBackground(new java.awt.Color(51, 102, 255));
        btnAgregar_Lote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar_Lote.setForeground(new java.awt.Color(51, 51, 51));
        btnAgregar_Lote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/1904677-add-addition-calculate-charge-create-new-plus_122527.png"))); // NOI18N
        btnAgregar_Lote.setText("Agregar");
        btnAgregar_Lote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_LoteActionPerformed(evt);
            }
        });

        txtLote.setBackground(new java.awt.Color(255, 204, 102));
        txtLote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLote.setForeground(new java.awt.Color(51, 51, 51));

        lblLote.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblLote.setForeground(new java.awt.Color(51, 51, 51));
        lblLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/temperature_icon-icons.com_65084.png"))); // NOI18N
        lblLote.setText("Lote:");

        txtId.setBackground(new java.awt.Color(255, 153, 102));
        txtId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(51, 51, 51));
        txtId.setCaretColor(new java.awt.Color(51, 51, 51));

        lblId_Lote.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblId_Lote.setForeground(new java.awt.Color(51, 51, 51));
        lblId_Lote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/idcard_119573.png"))); // NOI18N
        lblId_Lote.setText("Id:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblId_Lote, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLote, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre_Lote, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar_Lote)
                        .addGap(26, 26, 26)
                        .addComponent(btnModificar_Lote)
                        .addGap(27, 27, 27)
                        .addComponent(btnEliminar_Lote)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre_Lote))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId_Lote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLote)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar_Lote)
                    .addComponent(btnModificar_Lote, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar_Lote))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNombreActionPerformed
	// TODO add your handling code here:
	//servicio.cargarCombo(jcbNombre);
//
//	jcbNombre.addItemListener(new ItemListener() {
//	    @Override
//	    public void itemStateChanged(ItemEvent e) {
//		if (e.getStateChange() == ItemEvent.SELECTED) {
//		    txtId.setText((String) jcbNombre.getSelectedItem());
//		}
//	    }
//	});
//	jcbNombre.addItemListener(new ItemListener() {
//	    @Override
//	    public void itemStateChanged(ItemEvent e) {
//		if (e.getStateChange() == ItemEvent.SELECTED) {
//		    txtId.setText((String) jcbNombre.getSelectedItem());
//		}
//	    }
//	});
//	jcbNombre.addItemListener(new ItemListener() {
//	    @Override
//	    public void itemStateChanged(ItemEvent e) {
//		Producto productos = new Producto(){};
//		String mensaje;
//		if (jcbNombre.getSelectedItem().equals(productos.getNombre_pro()) ){
//		    String id_pro = txtId.getText();
//		    mensaje = servicio.agregarProducto(id_pro);
//		}
//	    }
//	});
//	JComboBox comboBoxRut = new JComboBox(new Object[]{});
//	comboBoxRut.addItemListener(new ItemListener() {
//	    public void itemStateChanged(ItemEvent nombre_pro) {
//		//En la variable arg0 se almacena el valor del Item seleccionado
//		System.out.println("Combo" + nombre_pro.getItem());
//		//haces un Select para buscar los datos a mostrar en los jtextfield
//		for (Producto producto : productos) {
//		    if (producto.getNombre_pro().equals(nombre_pro.getStateChange() == ItemEvent.SELECTED)) {
//			txtId.setText(producto.getId_pro());
//		    }
//		}
//	    }
//	});
    }//GEN-LAST:event_jcbNombreActionPerformed

    private void jcbNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbNombreItemStateChanged
	// TODO add your handling code here:
//	pro = (Producto)this.jcbNombre.getSelectedItem();
//	//txtId.setText(pro.getId_pro());
//	String id_pro = pro.getId_pro();
//	txtId.setText(id_pro);	
//	servicio.listarLote(jcbNombre, id_pro);
	//jcbNombre.removeAllItems();
	//jcbNombre.addItem("Seleciones un Producto");

	if (jcbNombre.getSelectedItem() == "Seleccione un Producto") {
	    txtId.setText("");
	    txtLote.setText("");
	} else {
	    //Producto pro = (Producto) this.jcbNombre.getSelectedItem();
	    Lote lot = (Lote) this.jcbNombre.getSelectedItem();
	    String id_pro = lot.getId_pro();
	    String nombre_pro = lot.getNombre_pro();
	    String id_lot = lot.getId_lot();
	    //Double temperatura_pro = pro.getTemperatura_pro();
	    //Double valorBase_pro = pro.getValorBase_pro();
	    txtId.setText(id_pro);
	    txtLote.setText(id_lot);

	}


    }//GEN-LAST:event_jcbNombreItemStateChanged

    private void jcbNombrePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbNombrePopupMenuWillBecomeInvisible
	// TODO add your handling code here:
//	String tmp = (String) jcbNombre.getSelectedItem();
//	//conn = new Conexion();
//	
//	con = conn.getCon();
//	String sql = "SELECT * FROM producto WHERE nombre_pro = ?";
//	try {
//	    
//	    ps = con.prepareStatement(sql);
//	    ps.setString(1, sql);
//	    rs = ps.executeQuery();
//	    if (rs.next()) {
//		String add = rs.getString("id_pro");
//		txtId.setText(add);
//	    }
//	} catch (Exception e) {
//	    JOptionPane.showMessageDialog(null, e);
//	}
    }//GEN-LAST:event_jcbNombrePopupMenuWillBecomeInvisible

    private void btnAgregar_LoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_LoteActionPerformed
	// TODO add your handling code here:
	String mensaje;
	if ((txtLote.getText().isEmpty()) || (txtId.getText().isEmpty())) {
	    JOptionPane.showMessageDialog(null, "Ingrese todo la información");
	} else {
	    String id_pro = txtId.getText();
	    String id_lot = txtLote.getText();
	    mensaje = servicio.agregarLote(id_pro, id_lot);
	    //txtLote.setText("");
	    JOptionPane.showMessageDialog(null, mensaje);
	}
    }//GEN-LAST:event_btnAgregar_LoteActionPerformed

    private void btnEliminar_LoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_LoteActionPerformed
	// TODO add your handling code here:
	String mensaje = "aqui";
	//String id_lot = Integer.valueOf(txtLote.getText());
	int fila = Integer.parseInt(txtLote.getText());
	//String lot = txtLote.getSelectedText();

	if (fila > 0) {
	    String id_lot = txtLote.toString();
	    mensaje = servicio.eliminarLote(txtLote);
	    //mostrarTabla();
	    //limpiar();
	    JOptionPane.showMessageDialog(null, mensaje);
	} else {
	    JOptionPane.showMessageDialog(null, "Seleccione lote a eliminar");
	}
    }//GEN-LAST:event_btnEliminar_LoteActionPerformed

    private void btnModificar_LoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar_LoteActionPerformed
	// TODO add your handling code here:
	String mensaje;
	int fila = Integer.parseInt(txtLote.getText());
	if ((fila < 0) || (txtId.getText().isEmpty()) || (txtLote.getText().isEmpty())) {
	    JOptionPane.showMessageDialog(null, "Seleccione lote a modificar");
	} else {
	    String producto = txtId.getText();
	    String lote = txtLote.getText();
	    mensaje = servicio.modificarProducto(producto, lote);
	    //mostrarTabla();
	    //limpiar();
	    JOptionPane.showMessageDialog(null, mensaje);
	}
    }//GEN-LAST:event_btnModificar_LoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(LoteFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(LoteFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(LoteFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(LoteFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new LoteFormulario().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar_Lote;
    private javax.swing.JButton btnEliminar_Lote;
    private javax.swing.JButton btnModificar_Lote;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbNombre;
    private javax.swing.JLabel lblId_Lote;
    private javax.swing.JLabel lblLote;
    private javax.swing.JLabel lblNombre_Lote;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLote;
    // End of variables declaration//GEN-END:variables
}
