/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Willydmq
 */
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import controlador.ProductoControl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import vista.LoteFormulario;

public class ProductoFormulario extends javax.swing.JFrame {

    DefaultTableModel Tproducto;
    ProductoControl servicio = new ProductoControl();
    //private ProductoControl productoControl;
    //private Producto producto;

    /**
     * Creates new form ProductoFormulario
     */
    public ProductoFormulario() {
	initComponents();

	mostrarTabla();
    }

    public void mostrarTabla() {
	String datos[] = new String[4];
	DefaultTableModel Tproducto = new DefaultTableModel();
	Tproducto = (DefaultTableModel) tbProducto.getModel();
	Tproducto.getDataVector().clear();
//        for(int i =0; i<Teditorial.getRowCount();i++){
//            Teditorial.removeRow(i);
//        }
	ArrayList<Producto> listaProducto = new ArrayList();
	listaProducto = servicio.listarProducto();
	for (Producto x : listaProducto) {
	    datos[0] = x.getId_pro();
	    datos[1] = x.getNombre_pro();
	    datos[2] = String.valueOf(x.getTemperatura_pro());
	    datos[3] = String.valueOf(x.getValorBase_pro());
	    Tproducto.addRow(datos);
	}
	Tproducto = (DefaultTableModel) tbProducto.getModel();
    }

    public void limpiar() {
	txtId.setText("");
	txtId.setEnabled(true);
	txtNombre.setText("");
	txtTemperatura.setText("");
	txtValorBase.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProducto = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtValorBase = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblTemperatura = new javax.swing.JLabel();
        txtTemperatura = new javax.swing.JTextField();
        lblValorBase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblId1 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        lblTemperatura1 = new javax.swing.JLabel();
        txtTemperatura1 = new javax.swing.JTextField();
        lblValorBase1 = new javax.swing.JLabel();
        txtValorBase1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAlmacen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Producto");
        setBackground(new java.awt.Color(204, 255, 204));
        setFont(new java.awt.Font("A1011Helvetika  TYGRA", 1, 10)); // NOI18N
        setLocation(new java.awt.Point(400, 100));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(252, 250, 236));

        tbProducto.setAutoCreateRowSorter(true);
        tbProducto.setBackground(new java.awt.Color(255, 255, 204));
        tbProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 0), new java.awt.Color(204, 204, 0)));
        tbProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Temperatura", "Valor Base"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProducto.setGridColor(new java.awt.Color(255, 255, 204));
        tbProducto.setSelectionBackground(new java.awt.Color(204, 204, 0));
        tbProducto.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tbProducto.setShowGrid(true);
        tbProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProducto);

        btnEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(51, 51, 51));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/trash_bin_icon-icons.com_67981.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(153, 255, 153));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(51, 51, 51));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/edit_modify_icon_149489.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(51, 102, 255));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(51, 51, 51));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/1904677-add-addition-calculate-charge-create-new-plus_122527.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtValorBase.setBackground(new java.awt.Color(102, 204, 255));
        txtValorBase.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtValorBase.setForeground(new java.awt.Color(51, 51, 51));

        lblId.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(51, 51, 51));
        lblId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/idcard_119573.png"))); // NOI18N
        lblId.setText("Id:");

        txtId.setBackground(new java.awt.Color(255, 153, 102));
        txtId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 0, 0));
        txtId.setCaretColor(new java.awt.Color(51, 51, 51));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/name_user_3716.png"))); // NOI18N
        lblNombre.setText("Nombre:");

        txtNombre.setBackground(new java.awt.Color(255, 153, 102));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setCaretColor(new java.awt.Color(51, 51, 51));

        lblTemperatura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblTemperatura.setForeground(new java.awt.Color(51, 51, 51));
        lblTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/temperature_icon-icons.com_65084.png"))); // NOI18N
        lblTemperatura.setText("Temperatura:");

        txtTemperatura.setBackground(new java.awt.Color(255, 204, 102));
        txtTemperatura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTemperatura.setForeground(new java.awt.Color(51, 51, 51));

        lblValorBase.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblValorBase.setForeground(new java.awt.Color(51, 51, 51));
        lblValorBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/savecostbudgetvaluepricecut_109773.png"))); // NOI18N
        lblValorBase.setText("Valor Base:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/symbol_medical_18040.png"))); // NOI18N
        jLabel1.setText("DROGUERIA -- COLOMBIA --");

        btnAgregar1.setBackground(new java.awt.Color(0, 153, 153));
        btnAgregar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar1.setForeground(new java.awt.Color(51, 51, 51));
        btnAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/1904677-add-addition-calculate-charge-create-new-plus_122527.png"))); // NOI18N
        btnAgregar1.setText("LOTE");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorBase)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtValorBase, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAgregar1))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(42, 42, 42)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTemperatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorBase, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnAgregar1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PRODUCTOS", jPanel1);

        jPanel2.setBackground(new java.awt.Color(252, 250, 236));

        jPanel3.setBackground(new java.awt.Color(252, 250, 236));

        lblId1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblId1.setForeground(new java.awt.Color(51, 51, 51));
        lblId1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/idcard_119573.png"))); // NOI18N
        lblId1.setText("Codigo:");

        txtId1.setBackground(new java.awt.Color(255, 153, 102));
        txtId1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtId1.setForeground(new java.awt.Color(255, 0, 0));
        txtId1.setCaretColor(new java.awt.Color(51, 51, 51));

        lblNombre1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/name_user_3716.png"))); // NOI18N
        lblNombre1.setText("Nombre:");

        txtNombre1.setBackground(new java.awt.Color(255, 153, 102));
        txtNombre1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre1.setCaretColor(new java.awt.Color(51, 51, 51));

        lblTemperatura1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblTemperatura1.setForeground(new java.awt.Color(51, 51, 51));
        lblTemperatura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/temperature_icon-icons.com_65084.png"))); // NOI18N
        lblTemperatura1.setText("Lote:");

        txtTemperatura1.setBackground(new java.awt.Color(255, 204, 102));
        txtTemperatura1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTemperatura1.setForeground(new java.awt.Color(51, 51, 51));

        lblValorBase1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblValorBase1.setForeground(new java.awt.Color(51, 51, 51));
        lblValorBase1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/savecostbudgetvaluepricecut_109773.png"))); // NOI18N
        lblValorBase1.setText("Id:");

        txtValorBase1.setBackground(new java.awt.Color(102, 204, 255));
        txtValorBase1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtValorBase1.setForeground(new java.awt.Color(51, 51, 51));

        tbAlmacen.setAutoCreateRowSorter(true);
        tbAlmacen.setBackground(new java.awt.Color(255, 255, 204));
        tbAlmacen.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 0), new java.awt.Color(204, 204, 0)));
        tbAlmacen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tbAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Lote", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAlmacen.setGridColor(new java.awt.Color(255, 255, 204));
        tbAlmacen.setSelectionBackground(new java.awt.Color(204, 204, 0));
        tbAlmacen.setSelectionForeground(new java.awt.Color(51, 51, 51));
        tbAlmacen.setShowGrid(true);
        tbAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAlmacenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbAlmacen);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTemperatura1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorBase1)
                            .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtValorBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTemperatura1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblId1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTemperatura1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTemperatura1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorBase1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ALMACEN", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("PRODUCTOS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
	//TODO add your handling code here:
	String mensaje;
	int fila;
	fila = tbProducto.getSelectedRow();
//	if(txtId.getText() != tbProducto.getValueAt(fila,0).toString()){
//		JOptionPane.showMessageDialog(null, "No se puede cambiar el ID");
//	}
//	if(((txtNombre.getText() == tbProducto.getValueAt(fila, 1)) && ((txtTemperatura.getText()) == tbProducto.getValueAt(fila, 2).toString()) && (txtValorBase.getText() == tbProducto.getValueAt(fila, 3).toString()))){
//	    JOptionPane.showMessageDialog(null, "Producto YA existe");
//	}
	if ((fila < 0) || (txtNombre.getText().isEmpty()) || (txtTemperatura.getText().isEmpty()) || (txtValorBase.getText().isEmpty())) {
	    JOptionPane.showMessageDialog(null, "Seleccione producto e ingrese nombre,temperatura ó valor base a modificar");
	} else {
	    String codigo = tbProducto.getModel().getValueAt(fila, 0).toString();
	    String nombre = txtNombre.getText();
	    double temperatura = Double.parseDouble(txtTemperatura.getText());
	    double valorBase = Double.parseDouble(txtValorBase.getText());
	    mensaje = servicio.modificarProducto(codigo, nombre, temperatura, valorBase);
	    mostrarTabla();
	    limpiar();
	    JOptionPane.showMessageDialog(null, mensaje);
	}

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
	// TODO add your handling code here:
	String mensaje;
	int fila;
	fila = tbProducto.getSelectedRow();
	if (fila >= 0) {
	    String id = tbProducto.getModel().getValueAt(fila, 0).toString();
	    mensaje = servicio.eliminarProducto(id);
	    mostrarTabla();
	    limpiar();
	    JOptionPane.showMessageDialog(null, mensaje);
	} else {
	    JOptionPane.showMessageDialog(null, "Seleccione producto a eliminar");
	}
    }//GEN-LAST:event_btnEliminarActionPerformed

        private void tbProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductoMouseClicked
	    // TODO add your handling code here:
	    int fila = tbProducto.rowAtPoint(evt.getPoint());
	    txtId.setText(tbProducto.getValueAt(fila, 0).toString());
	    txtId.setEnabled(false);
	    //setEnabled(false);
	    txtNombre.setText(tbProducto.getValueAt(fila, 1).toString());
	    txtTemperatura.setText(String.valueOf(tbProducto.getValueAt(fila, 2).toString()));
	    txtValorBase.setText(String.valueOf(tbProducto.getValueAt(fila, 3).toString()));
        }//GEN-LAST:event_tbProductoMouseClicked

    private void tbAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAlmacenMouseClicked
	// TODO add your handling code here:
    }//GEN-LAST:event_tbAlmacenMouseClicked

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
	// TODO add your handling code here:
	this.setVisible(true);
	LoteFormulario lf = new LoteFormulario();
	lf.setVisible(true);
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
	// TODO add your handling code here:
	String mensaje;
	if ((txtId.getText().isEmpty()) || (txtNombre.getText().isEmpty()) || (txtTemperatura.getText().isEmpty()) || (txtValorBase.getText().isEmpty())) {
	    JOptionPane.showMessageDialog(null, "Ingrese todo la información");
	} else {
	    String id_pro = txtId.getText();
	    String nombre_pro = txtNombre.getText();
	    String temperatura_pro = txtTemperatura.getText();
	    String valorBase_pro = txtValorBase.getText();
	    mensaje = servicio.agregarProducto(id_pro, nombre_pro, temperatura_pro, valorBase_pro);
	    mostrarTabla();
	    limpiar();
	    JOptionPane.showMessageDialog(null, mensaje);
	}
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(ProductoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(ProductoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(ProductoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(ProductoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new ProductoFormulario().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblTemperatura1;
    private javax.swing.JLabel lblValorBase;
    private javax.swing.JLabel lblValorBase1;
    private javax.swing.JTable tbAlmacen;
    private javax.swing.JTable tbProducto;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtTemperatura;
    private javax.swing.JTextField txtTemperatura1;
    private javax.swing.JTextField txtValorBase;
    private javax.swing.JTextField txtValorBase1;
    // End of variables declaration//GEN-END:variables

}
